version: "3"

services:
  app:
    build:
      context: .
    container_name: api-container
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - "/root/dostaff/config:/dostaff/config"
      - "/root/dostaff/log:/dostaff/log"