version: "3"

services:
  app:
    build:
      context: .
    container_name: api-container
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - "/root/dostuff/config:/dostuff/config"
      - "/root/dostuff/log:/dostuff/log"